# Generated by Django 5.1.6 on 2025-02-16 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255)),
                ("lyrics", models.TextField()),
                ("difficulty_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("words_learned", models.IntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music_app.song"
                    ),
                ),
            ],
        ),
    ]
